version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    #    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    #    expose:
    #      - 5432
    ports:
      - 5432:5432
    volumes:
      #      - "D:/checkVerification/RestDemo/db/data/postgres_db:/var/lib/postgresql/data"
      - pgdata:/var/lib/postgresql/data


  sping:
    image: springboot
    #    network_mode: bridge
    container_name: springboot
    build: ./
    #    expose:
    #      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
  #    links:
  #      - bd


volumes:
  pgdata:
#    driver: local
#    external: true